% Steady-state parameter file (CarnotCycle_sspar.r)
% Generated by MTT at Wed Mar  4 11:02:40 GMT 1998

% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% % Version control history
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% % $Id$
% % $Log$
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



% Steady-state states
MTTX1 := 	t_0*m*c_v; % CarnotCycle_cycle_gas (c)
MTTX2 := 	10.0;      % CarnotCycle_cycle_gas (c)
MTTX3 := 	m*c_v;	   % CarnotCycle_cycle_entropy (3)
MTTX4 := 	10.0;      % CarnotCycle_cycle_volume (3)

% Steady-state inputs
MTTU1 := 	0; % CarnotCycle (Heat)
MTTU2 := 	0; % CarnotCycle (Work)
;;END;
