% Steady-state parameter file (LiquidTurbine_sspar.r)
% Generated by MTT at Fri Nov 20 11:42:16 GMT 1998

% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% % Version control history
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% % $Id$
% % $Log$
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



% Steady-state states
MTTX1 := 	1; % LiquidTurbine (j_s)
MTTX2 := 	p_0*c/rho; % LiquidTurbine_C1 (tank) - pressure = p0
MTTX3 := 	t_0*p_0*c*c_p; % LiquidTurbine_C1 (tank) - temp = t0
% Steady-state inputs
MTTU1 := 	q_0; % LiquidTurbine (Heat)
MTTU2 := 	0; % LiquidTurbine (Work)
;;END;
