function [In] =  In_abg
# This function is the acausal bond graph representation of In
# Generated by MTT on Thu Mar 16 10:33:58 2000
# The file is in Octave format

# Subsystems and Ports

# Port Hy_out
  In.ports.Hy_out.type = "SS";
  In.ports.Hy_out.cr = "SS";
  In.ports.Hy_out.arg = "external,external";
  In.ports.Hy_out.repetitions = 1;
  In.ports.Hy_out.status = -1;
  In.ports.Hy_out.connections = [2 ];

# Port Th_out
  In.ports.Th_out.type = "SS";
  In.ports.Th_out.cr = "SS";
  In.ports.Th_out.arg = "external,external";
  In.ports.Th_out.repetitions = 1;
  In.ports.Th_out.status = -1;
  In.ports.Th_out.connections = [1 ];

# Component Hy_in
  In.subsystems.Hy_in.type = "SS";
  In.subsystems.Hy_in.cr = "SS";
  In.subsystems.Hy_in.arg = "p_1,internal";
  In.subsystems.Hy_in.repetitions = 1;
  In.subsystems.Hy_in.status = -1;
  In.subsystems.Hy_in.connections = [-2 ];

# Component Th_in
  In.subsystems.Th_in.type = "SS";
  In.subsystems.Th_in.cr = "SS";
  In.subsystems.Th_in.arg = "t_1,internal";
  In.subsystems.Th_in.repetitions = 1;
  In.subsystems.Th_in.status = -1;
  In.subsystems.Th_in.connections = [-1 ];

# Ordered list of Port names
  In.portlist(1,:) = "Hy_out";
  In.portlist(2,:) = "Th_out";

# Ordered list of subsystem names
  In.subsystemlist(1,:) = "Hy_in";
  In.subsystemlist(2,:) = "Th_in";

# Bonds 
  In.bonds = [
      1 1 
      1 1 
      ];

# Aliases 
# A double underscore __ represents a comma 
In.alias.out = "Th_out,Hy_out";
In.alias.in = "Th_out,Hy_out";
