function [Out] =  Out_abg
# This function is the acausal bond graph representation of Out
# Generated by MTT on Thu Mar 16 10:34:51 2000
# The file is in Octave format

# Subsystems and Ports

# Port Hy_in
  Out.ports.Hy_in.type = "SS";
  Out.ports.Hy_in.cr = "SS";
  Out.ports.Hy_in.arg = "external,external";
  Out.ports.Hy_in.repetitions = 1;
  Out.ports.Hy_in.status = -1;
  Out.ports.Hy_in.connections = [-1 ];

# Port Th_in
  Out.ports.Th_in.type = "SS";
  Out.ports.Th_in.cr = "SS";
  Out.ports.Th_in.arg = "external,external";
  Out.ports.Th_in.repetitions = 1;
  Out.ports.Th_in.status = -1;
  Out.ports.Th_in.connections = [-2 ];

# Component Hy_out
  Out.subsystems.Hy_out.type = "SS";
  Out.subsystems.Hy_out.cr = "SS";
  Out.subsystems.Hy_out.arg = "p_1,internal";
  Out.subsystems.Hy_out.repetitions = 1;
  Out.subsystems.Hy_out.status = -1;
  Out.subsystems.Hy_out.connections = [1 ];

# Component Th_out
  Out.subsystems.Th_out.type = "SS";
  Out.subsystems.Th_out.cr = "SS";
  Out.subsystems.Th_out.arg = "t_1,internal";
  Out.subsystems.Th_out.repetitions = 1;
  Out.subsystems.Th_out.status = -1;
  Out.subsystems.Th_out.connections = [2 ];

# Ordered list of Port names
  Out.portlist(1,:) = "Hy_in";
  Out.portlist(2,:) = "Th_in";

# Ordered list of subsystem names
  Out.subsystemlist(1,:) = "Hy_out";
  Out.subsystemlist(2,:) = "Th_out";

# Bonds 
  Out.bonds = [
      -1 -1 
      -1 -1 
      ];

# Aliases 
# A double underscore __ represents a comma 
Out.alias.in = "Th_in,Hy_in";
