function [Poly] =  Poly_abg
# This function is the acausal bond graph representation of Poly
# Generated by MTT on Thu Mar 16 10:35:48 2000
# The file is in Octave format

# Subsystems and Ports

# Port Pressure_1
  Poly.ports.Pressure_1.type = "SS";
  Poly.ports.Pressure_1.cr = "SS";
  Poly.ports.Pressure_1.arg = "external,external";
  Poly.ports.Pressure_1.repetitions = 1;
  Poly.ports.Pressure_1.status = -1;
  Poly.ports.Pressure_1.connections = [-2 ];

# Port Temperature_1
  Poly.ports.Temperature_1.type = "SS";
  Poly.ports.Temperature_1.cr = "SS";
  Poly.ports.Temperature_1.arg = "external,external";
  Poly.ports.Temperature_1.repetitions = 1;
  Poly.ports.Temperature_1.status = -1;
  Poly.ports.Temperature_1.connections = [-6 ];

# Port Pressure_2
  Poly.ports.Pressure_2.type = "SS";
  Poly.ports.Pressure_2.cr = "SS";
  Poly.ports.Pressure_2.arg = "external,external";
  Poly.ports.Pressure_2.repetitions = 1;
  Poly.ports.Pressure_2.status = -1;
  Poly.ports.Pressure_2.connections = [-4 ];

# Port Temperature_2
  Poly.ports.Temperature_2.type = "SS";
  Poly.ports.Temperature_2.cr = "SS";
  Poly.ports.Temperature_2.arg = "external,external";
  Poly.ports.Temperature_2.repetitions = 1;
  Poly.ports.Temperature_2.status = -1;
  Poly.ports.Temperature_2.connections = [8 ];

# Component r
  Poly.subsystems.r.type = "R";
  Poly.subsystems.r.cr = "Poly";
  Poly.subsystems.r.arg = "alpha";
  Poly.subsystems.r.repetitions = 1;
  Poly.subsystems.r.status = -1;
  Poly.subsystems.r.connections = [1 3 5 -7 ];

# Component zero
  Poly.subsystems.zero.type = "SS";
  Poly.subsystems.zero.cr = "SS";
  Poly.subsystems.zero.arg = "0,0";
  Poly.subsystems.zero.repetitions = 1;
  Poly.subsystems.zero.status = -1;
  Poly.subsystems.zero.connections = [-9 ];

# Component mtt1
  Poly.subsystems.mtt1.type = "AE";
  Poly.subsystems.mtt1.cr = "";
  Poly.subsystems.mtt1.arg = "";
  Poly.subsystems.mtt1.repetitions = 1;
  Poly.subsystems.mtt1.status = -1;
  Poly.subsystems.mtt1.connections = [2 -1 ];

# Component mtt2
  Poly.subsystems.mtt2.type = "AE";
  Poly.subsystems.mtt2.cr = "";
  Poly.subsystems.mtt2.arg = "";
  Poly.subsystems.mtt2.repetitions = 1;
  Poly.subsystems.mtt2.status = -1;
  Poly.subsystems.mtt2.connections = [4 -3 ];

# Component mtt3
  Poly.subsystems.mtt3.type = "AE";
  Poly.subsystems.mtt3.cr = "";
  Poly.subsystems.mtt3.arg = "";
  Poly.subsystems.mtt3.repetitions = 1;
  Poly.subsystems.mtt3.status = -1;
  Poly.subsystems.mtt3.connections = [6 -5 ];

# Component mtt4
  Poly.subsystems.mtt4.type = "1";
  Poly.subsystems.mtt4.cr = "";
  Poly.subsystems.mtt4.arg = "";
  Poly.subsystems.mtt4.repetitions = 1;
  Poly.subsystems.mtt4.status = -1;
  Poly.subsystems.mtt4.connections = [7 -8 9 ];

# Ordered list of Port names
  Poly.portlist(1,:) = "Pressure_1   ";
  Poly.portlist(2,:) = "Temperature_1";
  Poly.portlist(3,:) = "Pressure_2   ";
  Poly.portlist(4,:) = "Temperature_2";

# Ordered list of subsystem names
  Poly.subsystemlist(1,:) = "r   ";
  Poly.subsystemlist(2,:) = "zero";
  Poly.subsystemlist(3,:) = "mtt1";
  Poly.subsystemlist(4,:) = "mtt2";
  Poly.subsystemlist(5,:) = "mtt3";
  Poly.subsystemlist(6,:) = "mtt4";

# Bonds 
  Poly.bonds = [
      1 1 
      0 0 
      1 1 
      0 0 
      1 1 
      0 0 
      0 0 
      0 0 
      1 -1 
      ];

# Aliases 
# A double underscore __ represents a comma 
Poly.alias.out = "Temperature_2";
Poly.alias.P1 = "Pressure_1";
Poly.alias.P2 = "Pressure_2";
Poly.alias.T1 = "Temperature_1";
Poly.alias.T2 = "Temperature_2";
Poly.alias.alpha = "$1";
