function [SimpleGasTurbineABG] =  SimpleGasTurbineABG_abg
# This function is the acausal bond graph representation of SimpleGasTurbineABG
# Generated by MTT on Thu Mar 16 12:59:12 2000
# The file is in Octave format

# Subsystems and Ports

# Component c1
  SimpleGasTurbineABG.subsystems.c1.type = "Comb";
  SimpleGasTurbineABG.subsystems.c1.cr = "none";
  SimpleGasTurbineABG.subsystems.c1.arg = "m_c;v_c;r";
  SimpleGasTurbineABG.subsystems.c1.repetitions = 1;
  SimpleGasTurbineABG.subsystems.c1.status = -1;
  SimpleGasTurbineABG.subsystems.c1.connections = [14 -15 7 10 -11 ];

# Component j_s
  SimpleGasTurbineABG.subsystems.j_s.type = "I";
  SimpleGasTurbineABG.subsystems.j_s.cr = "lin";
  SimpleGasTurbineABG.subsystems.j_s.arg = "flow,j_s";
  SimpleGasTurbineABG.subsystems.j_s.repetitions = 1;
  SimpleGasTurbineABG.subsystems.j_s.status = -1;
  SimpleGasTurbineABG.subsystems.j_s.connections = [2 ];

# Component comp
  SimpleGasTurbineABG.subsystems.comp.type = "Pump";
  SimpleGasTurbineABG.subsystems.comp.cr = "none";
  SimpleGasTurbineABG.subsystems.comp.arg = "c_v;density,ideal_gas,r;alpha;effort,k";
  SimpleGasTurbineABG.subsystems.comp.repetitions = 1;
  SimpleGasTurbineABG.subsystems.comp.status = -1;
  SimpleGasTurbineABG.subsystems.comp.connections = [16 -14 1 12 -10 ];

# Component turb
  SimpleGasTurbineABG.subsystems.turb.type = "Pump";
  SimpleGasTurbineABG.subsystems.turb.cr = "none";
  SimpleGasTurbineABG.subsystems.turb.arg = "c_v;density,ideal_gas,r;alpha;effort,k";
  SimpleGasTurbineABG.subsystems.turb.repetitions = 1;
  SimpleGasTurbineABG.subsystems.turb.status = -1;
  SimpleGasTurbineABG.subsystems.turb.connections = [15 -17 -6 11 -13 ];

# Component Work
  SimpleGasTurbineABG.subsystems.Work.type = "SS";
  SimpleGasTurbineABG.subsystems.Work.cr = "SS";
  SimpleGasTurbineABG.subsystems.Work.arg = "0,external";
  SimpleGasTurbineABG.subsystems.Work.repetitions = 1;
  SimpleGasTurbineABG.subsystems.Work.status = -1;
  SimpleGasTurbineABG.subsystems.Work.connections = [4 ];

# Component Heat
  SimpleGasTurbineABG.subsystems.Heat.type = "SS";
  SimpleGasTurbineABG.subsystems.Heat.cr = "SS";
  SimpleGasTurbineABG.subsystems.Heat.arg = "0,external";
  SimpleGasTurbineABG.subsystems.Heat.repetitions = 1;
  SimpleGasTurbineABG.subsystems.Heat.status = -1;
  SimpleGasTurbineABG.subsystems.Heat.connections = [9 ];

# Component Speed
  SimpleGasTurbineABG.subsystems.Speed.type = "SS";
  SimpleGasTurbineABG.subsystems.Speed.cr = "SS";
  SimpleGasTurbineABG.subsystems.Speed.arg = "0,external";
  SimpleGasTurbineABG.subsystems.Speed.repetitions = 1;
  SimpleGasTurbineABG.subsystems.Speed.status = -1;
  SimpleGasTurbineABG.subsystems.Speed.connections = [5 ];

# Component T3
  SimpleGasTurbineABG.subsystems.T3.type = "SS";
  SimpleGasTurbineABG.subsystems.T3.cr = "SS";
  SimpleGasTurbineABG.subsystems.T3.arg = "external,external";
  SimpleGasTurbineABG.subsystems.T3.repetitions = 1;
  SimpleGasTurbineABG.subsystems.T3.status = -1;
  SimpleGasTurbineABG.subsystems.T3.connections = [-8 ];

# Component in
  SimpleGasTurbineABG.subsystems.in.type = "In";
  SimpleGasTurbineABG.subsystems.in.cr = "";
  SimpleGasTurbineABG.subsystems.in.arg = "";
  SimpleGasTurbineABG.subsystems.in.repetitions = 1;
  SimpleGasTurbineABG.subsystems.in.status = -1;
  SimpleGasTurbineABG.subsystems.in.connections = [-16 -12 ];

# Component out
  SimpleGasTurbineABG.subsystems.out.type = "Out";
  SimpleGasTurbineABG.subsystems.out.cr = "";
  SimpleGasTurbineABG.subsystems.out.arg = "";
  SimpleGasTurbineABG.subsystems.out.repetitions = 1;
  SimpleGasTurbineABG.subsystems.out.status = -1;
  SimpleGasTurbineABG.subsystems.out.connections = [17 13 ];

# Component mtt1
  SimpleGasTurbineABG.subsystems.mtt1.type = "1";
  SimpleGasTurbineABG.subsystems.mtt1.cr = "";
  SimpleGasTurbineABG.subsystems.mtt1.arg = "";
  SimpleGasTurbineABG.subsystems.mtt1.repetitions = 1;
  SimpleGasTurbineABG.subsystems.mtt1.status = -1;
  SimpleGasTurbineABG.subsystems.mtt1.connections = [-1 -2 -3 -5 6 ];

# Component mtt2
  SimpleGasTurbineABG.subsystems.mtt2.type = "Load";
  SimpleGasTurbineABG.subsystems.mtt2.cr = "";
  SimpleGasTurbineABG.subsystems.mtt2.arg = "";
  SimpleGasTurbineABG.subsystems.mtt2.repetitions = 1;
  SimpleGasTurbineABG.subsystems.mtt2.status = -1;
  SimpleGasTurbineABG.subsystems.mtt2.connections = [3 -4 ];

# Component mtt3
  SimpleGasTurbineABG.subsystems.mtt3.type = "PS";
  SimpleGasTurbineABG.subsystems.mtt3.cr = "";
  SimpleGasTurbineABG.subsystems.mtt3.arg = "";
  SimpleGasTurbineABG.subsystems.mtt3.repetitions = 1;
  SimpleGasTurbineABG.subsystems.mtt3.status = -1;
  SimpleGasTurbineABG.subsystems.mtt3.connections = [8 -7 -9 ];

# Ordered list of subsystem names
  SimpleGasTurbineABG.subsystemlist(1,:) = "c1   ";
  SimpleGasTurbineABG.subsystemlist(2,:) = "j_s  ";
  SimpleGasTurbineABG.subsystemlist(3,:) = "comp ";
  SimpleGasTurbineABG.subsystemlist(4,:) = "turb ";
  SimpleGasTurbineABG.subsystemlist(5,:) = "Work ";
  SimpleGasTurbineABG.subsystemlist(6,:) = "Heat ";
  SimpleGasTurbineABG.subsystemlist(7,:) = "Speed";
  SimpleGasTurbineABG.subsystemlist(8,:) = "T3   ";
  SimpleGasTurbineABG.subsystemlist(9,:) = "in   ";
  SimpleGasTurbineABG.subsystemlist(10,:) = "out  ";
  SimpleGasTurbineABG.subsystemlist(11,:) = "mtt1 ";
  SimpleGasTurbineABG.subsystemlist(12,:) = "mtt2 ";
  SimpleGasTurbineABG.subsystemlist(13,:) = "mtt3 ";

# Bonds 
  SimpleGasTurbineABG.bonds = [
      0 0 
      1 1 
      0 0 
      -1 -1 
      -1 -1 
      0 0 
      0 0 
      1 1 
      -1 -1 
      0 0 
      0 0 
      0 0 
      0 0 
      0 0 
      0 0 
      0 0 
      0 0 
      ];

# Aliases 
# A double underscore __ represents a comma 
# Explicit variable declarations
#VAR t_2
#VAR t_3
#VAR t_4
#VAR p_2
#VAR p_3
#VAR p_4
#VAR mdot
#VAR gamma_0
#VAR q_0
#VAR w_0
#VAR omega_0
#VAR r_p
#VAR c_p
#VAR mom_0
endfunction
