Document: mtt-examples
Title: Debian mtt-examples Manual
Author: <insert document author here>
Abstract: This manual describes what mtt-examples is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mtt-examples/mtt-examples.sgml.gz

Format: postscript
Files: /usr/share/doc/mtt-examples/mtt-examples.ps.gz

Format: text
Files: /usr/share/doc/mtt-examples/mtt-examples.text.gz

Format: HTML
Index: /usr/share/doc/mtt-examples/html/index.html
Files: /usr/share/doc/mtt-examples/html/*.html

  
