% Steady-state parameter file (NonlinearMSD_sspar.r)
% Generated by MTT at Thu Mar  7 10:39:15 GMT 2002

% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% % Version control history
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% % $Id$
% % $Log$
% % Revision 1.1  2000/12/28 09:32:04  peterg
% % Initial revision
% %
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%% This one corresponds to the unstretched spring at theta = pi/3 
%% Note that U is calculated to give equilibrium for all angles

alpha := pi/3;

% Steady-state states
MTTX1 := 	eta;     %Initial angle (corresponds to u=0)
MTTX2 := 	0;        %Initial anglular velocity
% Steady-state inputs
MTTU1 := 	k*(l^2)*cos(MTTX1/2)*2*(sin(MTTX1/2)-sin(alpha/2));
;;END;
