% Steady-state parameter file (TwoLinkGMV_sspar.r)
% Generated by MTT at Tue Apr 14 08:47:47 BST 1998

% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% % Version control history
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% % $Id$
% % $Log$
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



% Steady-state states
MTTX1 := 	0; % TwoLinkGMV_spec_1 (c_s)
MTTX2 := 	0; % TwoLinkGMV_spec_1 (j_s)
MTTX3 := 	0; % TwoLinkGMV_spec_2 (c_s)
MTTX4 := 	0; % TwoLinkGMV_spec_2 (j_s)
MTTX5 := 	0; % TwoLinkGMV_system_rod1 (J)
MTTX6 := 	0; % TwoLinkGMV_system_rod1_th (3)
MTTX7 := 	0; % TwoLinkGMV_system_rod2 (J)
MTTX8 := 	0; % TwoLinkGMV_system_rod2_th (3)
MTTX9 := 	0; % TwoLinkGMV_model_rod1_J (i)
MTTX10 := 	0; % TwoLinkGMV_model_rod1_th_c (c)
MTTX11 := 	0; % TwoLinkGMV_model_rod2_J (i)
MTTX12 := 	0; % TwoLinkGMV_model_rod2_th_c (c)
% Steady-state inputs
MTTU1 := 	1; % TwoLinkGMV (Ref_1)
MTTU2 := 	1; % TwoLinkGMV (Ref_2)
MTTU3 := 	0; % TwoLinkGMV (Tau_1)
MTTU4 := 	0; % TwoLinkGMV (Tau_2)
MTTU5 := 	0; % TwoLinkGMV_model_rod1_J (X)
MTTU6 := 	0; % TwoLinkGMV_model_rod1_th_c (X)
MTTU7 := 	0; % TwoLinkGMV_model_rod2_J (X)
MTTU8 := 	0; % TwoLinkGMV_model_rod2_th_c (X)
;;END;
