function sympar = ReactorTQ_sympar();
% sympar = ReactorTQ_sympar();
%System ReactorTQ, representation sympar, language m;
%File ReactorTQ_sympar.m;
%Generated by MTT on Thu Aug 24 14:47:48 BST 2000;
%
global ...
mtt_no_globals ;
  sympar.a 	= 1; # ReactorTQ
  sympar.b 	= 2; # ReactorTQ
  sympar.c 	= 3; # ReactorTQ
  sympar.c_0 	= 4; # ReactorTQ
  sympar.c_A 	= 5; # ReactorTQ
  sympar.c_B 	= 6; # ReactorTQ
  sympar.c_p 	= 7; # ReactorTQ
  sympar.e_1 	= 8; # ReactorTQ
  sympar.e_2 	= 9; # ReactorTQ
  sympar.e_3 	= 10; # ReactorTQ
  sympar.f_s 	= 11; # ReactorTQ
  sympar.h 	= 12; # Rate
  sympar.h_1 	= 13; # ReactorTQ
  sympar.h_2 	= 14; # ReactorTQ
  sympar.h_3 	= 15; # ReactorTQ
  sympar.k 	= 16; # Rate
  sympar.k_1 	= 17; # ReactorTQ
  sympar.k_2 	= 18; # ReactorTQ
  sympar.k_3 	= 19; # ReactorTQ
  sympar.n 	= 20; # Rate
  sympar.q 	= 21; # Rate
  sympar.q_1 	= 22; # ReactorTQ
  sympar.q_2 	= 23; # ReactorTQ
  sympar.q_3 	= 24; # ReactorTQ
  sympar.q_S 	= 25; # ReactorTQ
  sympar.rho 	= 26; # ReactorTQ
  sympar.t_0 	= 27; # ReactorTQ
  sympar.t_s 	= 28; # ReactorTQ
  sympar.v_r 	= 29; # ReactorTQ
  sympar.x1 	= 30; # ReactorTQ
  sympar.x2 	= 31; # ReactorTQ
  sympar.x3 	= 32; # ReactorTQ
