function [Comb] =  Comb_abg
# This function is the acausal bond graph representation of Comb
# Generated by MTT on Thu Mar 16 10:33:30 2000
# The file is in Octave format

# Subsystems and Ports

# Port Hydraulic_in
  Comb.ports.Hydraulic_in.type = "SS";
  Comb.ports.Hydraulic_in.cr = "SS";
  Comb.ports.Hydraulic_in.arg = "external,external";
  Comb.ports.Hydraulic_in.repetitions = 1;
  Comb.ports.Hydraulic_in.status = -1;
  Comb.ports.Hydraulic_in.connections = [-3 ];

# Port Hydraulic_out
  Comb.ports.Hydraulic_out.type = "SS";
  Comb.ports.Hydraulic_out.cr = "SS";
  Comb.ports.Hydraulic_out.arg = "external,external";
  Comb.ports.Hydraulic_out.repetitions = 1;
  Comb.ports.Hydraulic_out.status = -1;
  Comb.ports.Hydraulic_out.connections = [7 ];

# Port Heat
  Comb.ports.Heat.type = "SS";
  Comb.ports.Heat.cr = "SS";
  Comb.ports.Heat.arg = "external,external";
  Comb.ports.Heat.repetitions = 1;
  Comb.ports.Heat.status = -1;
  Comb.ports.Heat.connections = [-5 ];

# Port Thermal_in
  Comb.ports.Thermal_in.type = "SS";
  Comb.ports.Thermal_in.cr = "SS";
  Comb.ports.Thermal_in.arg = "external,external";
  Comb.ports.Thermal_in.repetitions = 1;
  Comb.ports.Thermal_in.status = -1;
  Comb.ports.Thermal_in.connections = [-2 ];

# Port Thermal_out
  Comb.ports.Thermal_out.type = "SS";
  Comb.ports.Thermal_out.cr = "SS";
  Comb.ports.Thermal_out.arg = "external,external";
  Comb.ports.Thermal_out.repetitions = 1;
  Comb.ports.Thermal_out.status = -1;
  Comb.ports.Thermal_out.connections = [6 ];

# Component P
  Comb.subsystems.P.type = "SS";
  Comb.subsystems.P.cr = "SS";
  Comb.subsystems.P.arg = "external,0";
  Comb.subsystems.P.repetitions = 1;
  Comb.subsystems.P.status = -1;
  Comb.subsystems.P.connections = [9 ];

# Component T
  Comb.subsystems.T.type = "SS";
  Comb.subsystems.T.cr = "SS";
  Comb.subsystems.T.arg = "external,0";
  Comb.subsystems.T.repetitions = 1;
  Comb.subsystems.T.status = -1;
  Comb.subsystems.T.connections = [8 ];

# Component pipe
  Comb.subsystems.pipe.type = "hPipe";
  Comb.subsystems.pipe.cr = "none";
  Comb.subsystems.pipe.arg = "m_c;v_c;r";
  Comb.subsystems.pipe.repetitions = 1;
  Comb.subsystems.pipe.status = -1;
  Comb.subsystems.pipe.connections = [5 3 -4 2 -1 ];

# Component mtt1
  Comb.subsystems.mtt1.type = "0";
  Comb.subsystems.mtt1.cr = "";
  Comb.subsystems.mtt1.arg = "";
  Comb.subsystems.mtt1.repetitions = 1;
  Comb.subsystems.mtt1.status = -1;
  Comb.subsystems.mtt1.connections = [1 -6 -8 ];

# Component mtt2
  Comb.subsystems.mtt2.type = "0";
  Comb.subsystems.mtt2.cr = "";
  Comb.subsystems.mtt2.arg = "";
  Comb.subsystems.mtt2.repetitions = 1;
  Comb.subsystems.mtt2.status = -1;
  Comb.subsystems.mtt2.connections = [4 -7 -9 ];

# Ordered list of Port names
  Comb.portlist(1,:) = "Hydraulic_in ";
  Comb.portlist(2,:) = "Hydraulic_out";
  Comb.portlist(3,:) = "Heat         ";
  Comb.portlist(4,:) = "Thermal_in   ";
  Comb.portlist(5,:) = "Thermal_out  ";

# Ordered list of subsystem names
  Comb.subsystemlist(1,:) = "P   ";
  Comb.subsystemlist(2,:) = "T   ";
  Comb.subsystemlist(3,:) = "pipe";
  Comb.subsystemlist(4,:) = "mtt1";
  Comb.subsystemlist(5,:) = "mtt2";

# Bonds 
  Comb.bonds = [
      0 0 
      0 0 
      0 0 
      0 0 
      0 0 
      0 0 
      0 0 
      1 1 
      1 1 
      ];

# Aliases 
# A double underscore __ represents a comma 
Comb.alias.out = "Thermal_out,Hydraulic_out";
Comb.alias.Hy_out = "Hydraulic_out";
Comb.alias.v_c = "$2";
Comb.alias.Th_in = "Thermal_in";
Comb.alias.r = "$3";
Comb.alias.Th_out = "Thermal_out";
Comb.alias.in = "Thermal_in,Hydraulic_in";
Comb.alias.Hy_in = "Hydraulic_in";
Comb.alias.m_c = "$1";
