function [hPipe] =  hPipe_abg
# This function is the acausal bond graph representation of hPipe
# Generated by MTT on Thu Mar 16 10:33:07 2000
# The file is in Octave format

# Subsystems and Ports

# Port Heat
  hPipe.ports.Heat.type = "SS";
  hPipe.ports.Heat.cr = "SS";
  hPipe.ports.Heat.arg = "external,external";
  hPipe.ports.Heat.repetitions = 1;
  hPipe.ports.Heat.status = -1;
  hPipe.ports.Heat.connections = [-3 ];

# Port Hydraulic_in
  hPipe.ports.Hydraulic_in.type = "SS";
  hPipe.ports.Hydraulic_in.cr = "SS";
  hPipe.ports.Hydraulic_in.arg = "external,external";
  hPipe.ports.Hydraulic_in.repetitions = 1;
  hPipe.ports.Hydraulic_in.status = -1;
  hPipe.ports.Hydraulic_in.connections = [-5 ];

# Port Hydraulic_out
  hPipe.ports.Hydraulic_out.type = "SS";
  hPipe.ports.Hydraulic_out.cr = "SS";
  hPipe.ports.Hydraulic_out.arg = "external,external";
  hPipe.ports.Hydraulic_out.repetitions = 1;
  hPipe.ports.Hydraulic_out.status = -1;
  hPipe.ports.Hydraulic_out.connections = [6 ];

# Port Thermal_in
  hPipe.ports.Thermal_in.type = "SS";
  hPipe.ports.Thermal_in.cr = "SS";
  hPipe.ports.Thermal_in.arg = "external,external";
  hPipe.ports.Thermal_in.repetitions = 1;
  hPipe.ports.Thermal_in.status = -1;
  hPipe.ports.Thermal_in.connections = [-2 ];

# Port Thermal_out
  hPipe.ports.Thermal_out.type = "SS";
  hPipe.ports.Thermal_out.cr = "SS";
  hPipe.ports.Thermal_out.arg = "external,external";
  hPipe.ports.Thermal_out.repetitions = 1;
  hPipe.ports.Thermal_out.status = -1;
  hPipe.ports.Thermal_out.connections = [7 ];

# Component P2T
  hPipe.subsystems.P2T.type = "TF";
  hPipe.subsystems.P2T.cr = "lin";
  hPipe.subsystems.P2T.arg = "flow,r*m/v";
  hPipe.subsystems.P2T.repetitions = 1;
  hPipe.subsystems.P2T.status = -1;
  hPipe.subsystems.P2T.connections = [5 -1 ];

# Component T2P
  hPipe.subsystems.T2P.type = "TF";
  hPipe.subsystems.T2P.cr = "lin";
  hPipe.subsystems.T2P.arg = "effort,r*m/v";
  hPipe.subsystems.T2P.repetitions = 1;
  hPipe.subsystems.T2P.status = -1;
  hPipe.subsystems.T2P.connections = [4 -6 ];

# Component mtt1
  hPipe.subsystems.mtt1.type = "0";
  hPipe.subsystems.mtt1.cr = "";
  hPipe.subsystems.mtt1.arg = "";
  hPipe.subsystems.mtt1.repetitions = 1;
  hPipe.subsystems.mtt1.status = -1;
  hPipe.subsystems.mtt1.connections = [1 2 3 -4 -7 ];

# Ordered list of Port names
  hPipe.portlist(1,:) = "Heat         ";
  hPipe.portlist(2,:) = "Hydraulic_in ";
  hPipe.portlist(3,:) = "Hydraulic_out";
  hPipe.portlist(4,:) = "Thermal_in   ";
  hPipe.portlist(5,:) = "Thermal_out  ";

# Ordered list of subsystem names
  hPipe.subsystemlist(1,:) = "P2T ";
  hPipe.subsystemlist(2,:) = "T2P ";
  hPipe.subsystemlist(3,:) = "mtt1";

# Bonds 
  hPipe.bonds = [
      0 0 
      0 0 
      1 1 
      0 0 
      0 0 
      0 0 
      0 0 
      ];

# Aliases 
# A double underscore __ represents a comma 
hPipe.alias.out = "Thermal_out,Hydraulic_out";
hPipe.alias.Hy_out = "Hydraulic_out";
hPipe.alias.Th_in = "Thermal_in";
hPipe.alias.r = "$3";
hPipe.alias.Th_out = "Thermal_out";
hPipe.alias.m = "$1";
hPipe.alias.v = "$2";
hPipe.alias.in = "Thermal_in,Hydraulic_in";
hPipe.alias.Hy_in = "Hydraulic_in";
