% Constitutive relation file for TankC (TankC_cr.r)
% Generated by MTT at Thu Mar  5 10:30:23 GMT 1998

OPERATOR TankC;

%Pressure
% -- not relevant here

%Temperature
FOR ALL COMP,rho,c_p,volume,Energy
LET TankC(COMP,rho,c_p,volume,effort,1,
	Energy,state,1
	) = Energy/(volume*rho*c_p);

END;
