% Constitutive relation file for NozzleFlow (NozzleFlow_cr.r)
% Generated by PJG at Wed Apr 8 09:30 GMT 1998


% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% % Version control history
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% % $Id$
% % $Log$
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



OPERATOR NozzleFlow;
% Ideal gas - but polytropic expansion
FOR ALL R, n, p1, p2, T1, A, Nothing
LET NozzleFlow(R,n,flow,5,
	p1,effort,1,
	p2,effort,2,
	T1,effort,3,
	A,effort,4,
	Nothing,effort,5
	) = A*p1*( (2*n/(n-1)) * (1/(R*T1)) * 
                ((p2/p1)^(2/n)) * (1 - (p2/p1)^(n-1/n) ) ^(1/2)
                );

END;
